#!/usr/bin/env python3
"""Flask server for the commons demo.

The same four routes as the FastAPI server, registered by the same call:
`srv.register_flask` puts login, context refresh, the dispatcher and info on
whatever it is given — here the application itself, because this file *is* the
application. Plugin loading, model generation and the admin seed come from
kite.py, so both servers and the smoke test run the same application.

Having the pair here is what makes double framework support a property that is
checked rather than an intention: nothing else exercises the Flask path.

Run from this directory:  uv run server_flask.py
"""
import os

from flask import Flask

import kite
import kitebase.server_utils as srv

# ── Application ─────────────────────────────────────────────────────────────

kitebase_app, plugins = kite.setup()

import model  # type: ignore  # generated by kite.setup()  # noqa: E402

kitebase_app.initialize_db(plugins.config["db_engine"], model)
plugins.load_all_locales()
kite.seed(kitebase_app, model)

# 32 bytes at least: below that PyJWT warns that the key is weak for
# HS256, and a warning nobody can act on is a warning people learn to skip.
SECRET_KEY = os.environ.get("SECRET_KEY", "development-secret-key-not-for-service")

app = Flask(__name__)
app.config["SECRET_KEY"] = SECRET_KEY

# ── Routes ──────────────────────────────────────────────────────────────────

srv.register_flask(app, kitebase_app, plugins, SECRET_KEY)


# A built client, when there is one: `clientui/`, mounted where `client:` in
# config.yaml says - at the root, the demo being the application itself.
srv.serve_client_flask(app, os.path.dirname(os.path.abspath(__file__)), plugins.config)


if __name__ == "__main__":
    port = plugins.config.get("api", {}).get("port", 8302)
    print(f"\n🚀 Kitebase commons demo (Flask) on port {port}\n")
    app.run(host="0.0.0.0", port=port)
