#!/usr/bin/env python3
"""FastAPI server for the commons demo.

Four routes and nothing else: login, context refresh, the dispatcher that
carries every other operation, and info — registered by `srv.register_fastapi`
on the application itself, because this file *is* the application. Plugin
loading, model generation and the admin seed come from kite.py, so the smoke
test and the server always run the same application.

Run from this directory:  uv run server_fastapi.py
"""
import os

from fastapi import FastAPI

import kite
import kitebase.server_utils as srv

# ── Application ─────────────────────────────────────────────────────────────

kitebase_app, plugins = kite.setup()

import model  # type: ignore  # generated by kite.setup()  # noqa: E402

kitebase_app.initialize_db(plugins.config["db_engine"], model)
plugins.load_all_locales()
kite.seed(kitebase_app, model)

# 32 bytes at least: below that PyJWT warns that the key is weak for
# HS256, and a warning nobody can act on is a warning people learn to skip.
SECRET_KEY = os.environ.get("SECRET_KEY", "development-secret-key-not-for-service")

app = FastAPI(
    title="Kitebase commons demo",
    description="Reference app for the shared plugins",
    version=plugins.config.get("version", "0.0.0"),
)

# ── Routes ──────────────────────────────────────────────────────────────────

srv.register_fastapi(app, kitebase_app, plugins, SECRET_KEY)


# A built client, when there is one: `clientui/`, mounted where `client:` in
# config.yaml says - at the root, the demo being the application itself. Last,
# so the API routes win.
srv.serve_client_fastapi(app, os.path.dirname(os.path.abspath(__file__)), plugins.config)


if __name__ == "__main__":
    import uvicorn

    port = plugins.config.get("api", {}).get("port", 8302)
    print(f"\n🚀 Kitebase commons demo on port {port}")
    print(f"📖 OpenAPI docs: http://localhost:{port}/docs\n")
    uvicorn.run(app, host="0.0.0.0", port=port, log_level="info")
